name: Delete old packages
description: Deletes old package versions

inputs:
  owner:
    description: >-
      Owner of the repo containing the package(s).
      Defaults to the owner of the repo running the action.
    required: false

  repo:
    description: >-
      Repo containing the package(s).
      Defaults to the repo running the action.
    required: false

  package-pattern:
    description: >-
      Regex pattern for packages to find old versions within
    required: true

  version-pattern:
    description: >-
      Regex pattern for package versions to delete
    required: false

  keep:
    description: >-
      Number of versions to exclude from deletions.
      Defaults to 10.
    required: false

  token:
    description: >-
      Token with the necessary scopes to delete and list package versions.
      Defaults to github.token scoped to the repo running the action. To delete package versions
      of a package outside the repo the action is running in use a Personal Access Token stored as a secret.
    required: false
    default: ${{ github.token }}

  dry-run:
    description: >-
      If the action should only print what it would delete instead of actually deleting.
    required: false
    default: "false"

runs:
  using: node12
  main: dist/index.js
