allowBuilds:
  msw: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
trustPolicy: no-downgrade
overrides:
  semver: ^7.7.4
  "@actions/core": ^3.0.0
  "@actions/github": ^9.1.0
  "@octokit/core": ^7.0.6
  "@octokit/endpoint": ^11.0.3
