name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v2.1.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - run: yarn install
      - run: yarn lint
      - run: yarn test

      - if: github.ref == 'refs/heads/main'
        run: yarn build

      - if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build
