name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm verify

      - if: github.ref == 'refs/heads/main'
        run: pnpm build

      - if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Build
